Afegir acta 0923
GeeksCAT/associacio pull request #32
Opened 2020-09-23 19:13 UTC by jbagot

2020-09-25 11:31 UTC, XaviTorello requested changes
Gràcies @jbagot 🍻 

Afegeixo algunes notes

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +- Crear definició de grup treball
Tasca per @GeeksCAT/core de repassar i afegir conceptes GT fins a principis de la setmana vinent (27/09/2020)

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +- Fer doodle per escollir data per la sessió inaugural i després presentar-ho als socis.
Tasca per @XaviTorello (preparar Doodle) i per @GeeksCAT/core per votar millors opcions.

Vam quedar que escolliriem les 2 més votades, i passariem nou Doodle amb aquestes opcions a tota la llista de socis, oi?

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +
Faltaria @francescarpi emputxa https://github.com/GeeksCAT/associacio/issues/24

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +
També faltaria @francescarpi i @XaviTorello preparen landing page pel hacktoberfest Geeks.CAT

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +
@jbagot estudiar eina inicial i definir amb issues què volem millorar

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +
@GeeksCAT/core decidir com ens volem involucrar en el hackathon (quina branca i si la volem liderar)

2020-09-25 11:31 UTC, XaviTorello commented on actes/2020/0923.rst
> +Si pertoca o si no queden integrades dins de l'agenda
Em sembla que això sobra

2020-12-07 19:37 UTC, jbagot commented on actes/2020/0923.rst
> +- Crear definició de grup treball
done

2020-12-07 19:37 UTC, jbagot commented on actes/2020/0923.rst
> +- Fer doodle per escollir data per la sessió inaugural i després presentar-ho als socis.
done

2020-12-07 19:37 UTC, jbagot commented on actes/2020/0923.rst
> +
done

2020-12-07 19:37 UTC, jbagot commented on actes/2020/0923.rst
> +Si pertoca o si no queden integrades dins de l'agenda
one

2020-12-07 22:33 UTC, XaviTorello approved these changes
Many thanks @jbagot

2020-12-07 22:33 UTC, merged