Create 0307
GeeksCAT/associacio pull request #43
Opened 2022-03-07 17:03 UTC by jbagot

2022-03-07 20:31 UTC, XaviTorello requested changes
Gràcies @jbagot, només quatre xorrades :)

2022-03-07 20:31 UTC, XaviTorello commented on actes/2022/0307
> +# Reunió 2022/03/07
Rename file to .md :)

2022-03-07 20:31 UTC, XaviTorello commented on actes/2022/0307
> +  - Modificar DNS. @xavitorello ho revisa, si algú més hi pot assistir millor així es pot traspassar el coneixament.
Typo: coneixement

2022-03-07 20:31 UTC, XaviTorello commented on actes/2022/0307
> +  - @VictorMartin enviarà email per saber com ho cobrem.
Teniu el link de la resolució a mà? Per linkar-la aquí

2022-03-07 20:31 UTC, XaviTorello commented on actes/2022/0307
> +
Faltaria 10. Acordem propera reunió JD pel XXX, estic amb el mòbil si no ho afegia jo mateix

2022-03-14 16:30 UTC, jbagot commented on actes/2022/0307
> +  - Modificar DNS. @xavitorello ho revisa, si algú més hi pot assistir millor així es pot traspassar el coneixament.
solved

2022-04-12 15:38 UTC, merged